version: 0.2

env:
  variables:
    REGION: ap-south-1
    AWS_ACCOUNT_ID: 618060700241
    ECR_REPO: sample-webapp
    PORT: 8080
  exported-variables:
    - IMAGE_TAG

phases: 
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing git"
      - yum install git -y
      - echo "Successfully installed git"
  
  pre_build:
    commands:
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo "Running Tests for Build "
      - mvn test
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Login Successful"
  
  build:
    commands:
      - echo "Build starting"
      - mvn clean package -DskipTests
      - echo "Listing target folder"
      - ls target/
      - echo "Building docker image"
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Succesfully pushed $ECR_REPO:$IMAGE_TAG to ECR"
      - echo "updating ecs service"
      - aws ecs update-service --cluster sample-webapp-cluster-latest --service sample-webapp-service --force-new-deployment --region $REGION
      - echo "ECS update triggered"
artifacts:
  files:
    - 'sample-webapp-1.0.jar'
  base-directory: target

cache:
  paths:
    - /root/.m2/**/*
