version: 0.2

env:
  variables:
    REGION: ap-south-1
    AWS_ACCOUNT_ID: 618060700241
    ECR_REPO: sample-webapp
    IMAGE_TAG: 1.0
    PORT: 8080

phases: 
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing git"
      - yum install git -y
      - echo "Successfully installed git"
  
  pre_build:
    commands:
      - echo "Running Tests for Build "
      - mvn test
      - echo "Logging into ECR"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Login Successful"
  
  build:
    commands:
      - echo "Build starting"
      - mvn clean package
      - echo "Building docker image"
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Succesfully pushed $ECR_REPO:$IMAGE_TAG to ECR"
artifacts:
  files:
    - '*.jar'
  base-directory: target

cache:
  paths:
    - /root/.m2/**/*
